version: '2'

services:

    elasticsearch: # Requests to this DNS elasticsearch:9200
        container_name: elasticsearch-cinema
        image: elasticsearch:5-alpine
        ports:
            - '9200:9200' # REST
            - '9300:9300' # Cross elastic nodes communication
        volumes:
            - node-cinema-elastic:/usr/share/elasticsearch/data
        networks:
            elk:

    kibana:
        container_name: kibana-cinema
        image: kibana:5
        ports:
            - '5601:5601'
        links: 
            - elasticsearch:elasticsearch-cinema
        depends_on:
            - elasticsearch
        networks:
            - elk

    logstash:
        container_name: logstash-cinema
        image: logstash:5-alpine
        ports:
            - '9500:9600'
        links:
            - elasticsearch:elasticsearch-cinema
        volumes:
            - ./logstash:/config-dir/
        command: -f /config-dir/logstash.conf
        depends_on:
            - elasticsearch
        networks:
            - elk

    node-cinema:
        container_name: node-cinema
        image: victoraweb/node-cinema
        build:
            context: .
            dockerfile: ./Dockerfile
        # command: node_modules/.bin/nodemon --exec npm start
        environment:
            NODE_ENV: development
            LOGSTASH_CONFIGS: '{ "host": "logstash", "port": "9500", "node_name": "node-cinema-logs" }' # The host will be the service name in this file
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        depends_on:
            - logstash
        networks:
            - elk

volumes:
    node-cinema-elastic:
networks:
    elk: