version: 2

jobs:
    build:
        working_directory: ~/tmp
        docker:
            - image: circleci/node:7
        steps:
            - checkout # circleci is aware of the current git repo
            - run: npm install
            - run: make tests

